"""The published-suite-count guard.

docs/testing.md published a table of pass counts per install configuration.
Every row of it was wrong by the time anyone looked: the `full` row was ~670
passes behind, the `base` skip figure in the table disagreed with the `base`
skip figure four paragraphs below it, and underneath both sat a retraction of a
third number that had been published for two minor releases against a CI job
that was red the whole time. It was hand-corrected three times and went stale
again after each one, because nobody can build all five configurations on one
machine and a one-process full run has crashed the machine that comes closest.

The table is deleted; the counts live in the CI log of the job that measured
them. This test is what keeps it deleted. A number that cannot be regenerated
cannot be checked, so the only place it can be wrong is in front of a reader who
has no way to notice — which is exactly what happened, three times.

The escape hatch is deliberate and deliberately visible: a `<!-- suite-count-ok:
reason -->` marker on the same line. That is a thing a reviewer sees in the diff
and has to agree with, unlike a number quietly typed into a table.
"""

import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS_DIR = os.path.join(REPO_ROOT, "docs")

# Three or more digits immediately followed by `passed` / `skipped` / `xfailed`,
# i.e. the tail of a `python -m pytest -q` summary line pasted into prose. Two
# digits are left alone on purpose: "0/60", "21 failures" and "7 rules" are
# claims about corpora and package data, not about the size of the suite, and
# they are regenerable from a command in the doc that carries them.
_COUNT = re.compile(r"(?<![\w.])\d{3,}\s+(?:passed|skipped|xfailed)\b")

# Same line, anywhere on it. Forcing a reason into the marker means the opt-out
# cannot be exercised by reflex.
_ALLOW = re.compile(r"<!--\s*suite-count-ok:\s*\S.*?-->")


def _markdown_files():
    paths = [os.path.join(REPO_ROOT, "README.md")]
    for name in sorted(os.listdir(DOCS_DIR)):
        if name.endswith(".md"):
            paths.append(os.path.join(DOCS_DIR, name))
    return paths


def test_docs_publish_no_unmarked_suite_counts():
    offenders = []
    for path in _markdown_files():
        with open(path, encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, start=1):
                if not _COUNT.search(line):
                    continue
                if _ALLOW.search(line):
                    continue
                rel = os.path.relpath(path, REPO_ROOT)
                hit = _COUNT.search(line).group(0)
                offenders.append(f"{rel}:{lineno}: {hit!r} in: {line.strip()}")

    assert not offenders, (
        "A suite count is published in the docs again. A pass count cannot be "
        "regenerated by a reader — no reader can build all five install "
        "configurations, and the last hand-maintained table was ~670 passes "
        "stale across three separate fix-up attempts while reading as evidence. "
        "Cite the CI job that prints it, or add "
        "`<!-- suite-count-ok: <why this one is checkable> -->` on the line.\n  "
        + "\n  ".join(offenders)
    )


def test_the_guard_can_actually_fail(tmp_path):
    """Non-vacuity: the matcher fires on the shape it claims to catch.

    Without this, the guard above is indistinguishable from a guard whose regex
    never matches anything — the failure mode that produced this repo's other
    vacuous gates. Both a plain summary tail and the markdown-table form the
    deleted table used must trip it, and the marker must suppress it.
    """
    assert _COUNT.search("| `full` (CI job) | ... | **7664 passed, 137 skipped** |")
    assert _COUNT.search("7603 passed, 163 skipped, 0 failed")
    assert _COUNT.search("**8432 passed, 137 skipped, 8 xfailed**")

    # Below the threshold, or not a suite summary at all: left alone.
    assert not _COUNT.search("nested-A2A structural FP gate PASS (0/60)")
    assert not _COUNT.search("it reported **21 failures**, because httpx")
    assert not _COUNT.search("assert len(js) == 7, 'expected 7 rules JSON'")

    marked = "7453 passed, 6 skipped <!-- suite-count-ok: retracted figure -->"
    assert _COUNT.search(marked) and _ALLOW.search(marked)

    # A marker with no reason does not count as a marker.
    assert not _ALLOW.search("7453 passed <!-- suite-count-ok: -->")
